#include "static.h"

// Centralized definitions to avoid multiple definition errors
const String appVersion = "v1.93";
#ifndef CUSTOM_APPNAME
const String appName = "WiTcontroller";
#else
const String appName = CUSTOM_APPNAME;
#endif

const String menu_text[14] = {
  MENU_TEXT_MENU,
  MENU_TEXT_MENU_HASH_IS_FUNCTIONS,
  MENU_TEXT_FINISH,
  MENU_TEXT_CANCEL,
  MENU_TEXT_SHOW_DIRECT,
  MENU_TEXT_ROSTER,
  MENU_TEXT_TURNOUT_LIST,
  MENU_TEXT_ROUTE_LIST,
  MENU_TEXT_FUNCTION_LIST,
  MENU_TEXT_SELECT_WIT_SERVICE,
  MENU_TEXT_SELECT_WIT_ENTRY,
  MENU_TEXT_SELECT_SSIDS,
  MENU_TEXT_SELECT_SSIDS_FROM_FOUND,
  MENU_TEXT_ENTER_SSID_PASSWORD
};

// Definition for extern declared in static.h
String witServerIpAndPortEntryMask = "###.###.###.###:#####";

// Added moved constant definitions from static.h to resolve Arduino IDE multiple inclusion redefinition errors
const String label_track_power = "TRK";

const int glyph_heartbeat_off = 0x00b7;
const int glyph_track_power = 0x00eb;
const int glyph_speed_step = 0x00d6;

#ifndef USER_DEFINED_MENUS
const String menuText[20][2] = {
  {MENU_ITEM_TEXT_TITLE_FUNCTION,              MENU_ITEM_TEXT_MENU_FUNCTION},
  {MENU_ITEM_TEXT_TITLE_ADD_LOCO,              MENU_ITEM_TEXT_MENU_ADD_LOCO},
  {MENU_ITEM_TEXT_TITLE_DROP_LOCO,             MENU_ITEM_TEXT_MENU_DROP_LOCO_REAL},
  {MENU_ITEM_TEXT_TITLE_TOGGLE_DIRECTION,      MENU_ITEM_TEXT_MENU_NA},
  {MENU_ITEM_TEXT_TITLE_SPEED_STEP_MULTIPLIER, MENU_ITEM_TEXT_MENU_NA},
  {MENU_ITEM_TEXT_TITLE_THROW_POINT,           MENU_ITEM_TEXT_MENU_THROW_POINT},
  {MENU_ITEM_TEXT_TITLE_CLOSE_POINT,           MENU_ITEM_TEXT_MENU_CLOSE_POINT},
  {MENU_ITEM_TEXT_TITLE_ROUTE,                 MENU_ITEM_TEXT_MENU_ROUTE},
  {MENU_ITEM_TEXT_TITLE_TRACK_POWER,           MENU_ITEM_TEXT_MENU_NA},
  {MENU_ITEM_TEXT_TITLE_EXTRAS,                MENU_ITEM_TEXT_MENU_EXTRAS},
  {EXTRA_MENU_TEXT_CHAR_FUNCTION_KEY_TOGGLE,   MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_EDIT_CONSIST,          MENU_ITEM_TEXT_MENU_EDIT_CONSIST},
  {EXTRA_MENU_TEXT_CHAR_TBA,                   MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_HEARTBEAT_TOGGLE,      MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_INCREASE_MAX_THROTTLES,MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_DECREASE_MAX_THROTTLES,MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_DISCONNECT,            MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_OFF_SLEEP,             MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_CHAR_DROP_BEFORE_ACQUIRE_TOGGLE, MENU_ITEM_TEXT_MENU_NA},
  {EXTRA_MENU_TEXT_SAVE_CURRENT_LOCOS,         MENU_ITEM_TEXT_MENU_NA}
};
#else
const String menuText[20][2] = MENU_STRUCTURE;
#endif

#ifndef USER_DEFINED_MENUS
const int menuCharsRequired[20] = {
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_ONE_OR_MORE_CHARS,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_SUB_MENU,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND,
  MENU_ITEM_TYPE_DIRECT_COMMAND
};
#else
const int menuCharsRequired[20] = MENU_CHARS_REQUIRED;
#endif


#ifdef  DISPLAY_SPEED_AS_PERCENT
const bool speedDisplayAsPercent = DISPLAY_SPEED_AS_PERCENT;
#else
const bool speedDisplayAsPercent = false;
#endif

#ifdef  DISPLAY_SPEED_AS_0_TO_28
const bool speedDisplayAs0to28 = DISPLAY_SPEED_AS_0_TO_28;
#else
const bool speedDisplayAs0to28 = false;
#endif

const char ssidPasswordBlankChar = 164;
